---
version: '3.1'
services:
##############################################################
# sinatra_template
##############################################################
  gelf_proxy:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/app
    ports:
      - 4567:4567
    env_file: env
